### PR TITLE
Components and props Sinhalese Translation completed

### PR DESCRIPTION
**Pull request by Menuka5**
Please let me know if any update needed

### CODE REVIEW

**Comment by pavinthan** [comment]
thanks @Menuka5

**Comment by Menuka5** [comment]
@pavinthan Can you Tick on  **Components and Props (@Menuka5)** https://github.com/reactjs/si.reactjs.org/issues/1 

I can't update it

**Comment by pavinthan** [comment]
Ohh sorry, updated now 😄

**Comment by Menuka5** [comment]
Thanks @pavinthan

**Pull request merged**
