### PR TITLE
Sinhala translations home page

### PR DESCRIPTION
**Pull request by ksenginew**
Completed Home page. Please review this pr.
Personally built this site with [Vercel](https://vercel.com) at https://si-reactjs-org-git-home-ksenginew.vercel.app/

### CODE REVIEW

**Comment by pavinthan** [comment]
@ksenginew could you please use the common name in the codebase as default that helps to match with the base template.

**Comment by ksenginew** [comment]
> @ksenginew could you please use the common name in the codebase as default that helps to match with the base template.

@pavinthan Should I close this pr to do it? Please give me the instructions.

**Comment by pavinthan** [comment]
@ksenginew no need, just change the names to any common names and update this PR please refer other languages contribution

Thank you for your support

**Comment by ksenginew** [comment]
@pavinthan Done. Is it ok?

> Accidentally closed this pr so reopened it.

**Comment by ksenginew** [comment]
@pavinthan can you review and accept this pr?

**Review by ksenginew — COMMENTED** [review]
reviewed again

**Comment by ksenginew** [comment]
> @pavinthan can you review and accept this pr?

???

**Comment by pavinthan** [comment]
Sure, I'll do that

**Comment by pavinthan** [comment]
@ksenginew could you please change the labels and headers?

Eg: In External Plugins example
We can change the label of "Enter some markdown" and Input-Output

**Comment by ksenginew** [comment]
Hi @pavinthan

It's done. I wonder how I missed it.

Thanks

**Comment by ksenginew** [comment]
@pavinthan ???

**Comment by ksenginew** [comment]
@pavinthan , All the things are fixed.
can you review and accept this pr?

**Comment by ksenginew** [comment]
@pavinthan @reactjs,

I am can't wait anymore for this pr. But I won't close this pr.

Thanks

**Comment by pavinthan** [comment]
@ksenginew sorry for the delay, we will review this ASAP

**Comment by ghost** [comment]
> I am can't wait anymore for this pr. But I won't close this pr.

While I appreciate that you are into coding and contributing to open source at such a young age, I also would like to suggest you to be polite in discussions. You may be busy with other work and want to see this merged soon, so do the maintainers. Please be mindful of communication and the tone, because software dev is a team work and poor/unhealthy communication ruins it.

Thanks.

**Comment by ksenginew** [comment]
@siri-ayya I'm really sorry. I'll try to be polite.

Thanks

**Pull request closed without merging**
